### ISSUE TITLE
小狼毫部分亂碼

### ISSUE THREAD

**Issue by spew8712** [rime-aca/rime-middle-chinese-phonetics#1]
如圖，在小狼毫使用時，會遇到不少亂碼問題。是不是comment_format中，有部分轉換出了問題？

![圖片](https://user-images.githubusercontent.com/30714211/120957989-4f4faa00-c789-11eb-9168-7c681d27e07b.png)

反而2014年的2.2版無此問題

![圖片](https://user-images.githubusercontent.com/30714211/120958756-ef5a0300-c78a-11eb-80f6-99de9108e105.png)

**Comment by LEOYoon-Tsaw** [comment]
<img width="376" alt="image" src="https://user-images.githubusercontent.com/4469383/124950302-4815f900-dfe0-11eb-92cd-0fecc0d2ccdf.png">
我未遇此問題，無法復現
